# Generated by Django 6.0.1 on 2026-02-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_jobanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalysis',
            name='feedback',
            field=models.JSONField(default=list),
        ),
    ]
